// <auto-generated />
using System;
using Fitness_Tracker_App_00012951.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fitness_Tracker_App_00012951.Migrations
{
    [DbContext(typeof(GeneralDBContext))]
    partial class GeneralDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Fitness_Tracker_App_00012951.Models.Workout", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<double?>("Calories_burned")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<double?>("Duration")
                        .IsRequired()
                        .HasColumnType("float");

                    b.Property<int?>("WorkoutTypeID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("WorkoutTypeID");

                    b.ToTable("Workouts");
                });

            modelBuilder.Entity("Fitness_Tracker_App_00012951.Models.WorkoutType", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("WorkoutTypes");
                });

            modelBuilder.Entity("Fitness_Tracker_App_00012951.Models.Workout", b =>
                {
                    b.HasOne("Fitness_Tracker_App_00012951.Models.WorkoutType", "WorkoutType")
                        .WithMany()
                        .HasForeignKey("WorkoutTypeID");

                    b.Navigation("WorkoutType");
                });
#pragma warning restore 612, 618
        }
    }
}
